import { MetadataRoute } from 'next'

export default function robots(): MetadataRoute.Robots {
  const baseUrl = 'https://saeedpay.com'
  
  return {
    rules: [
      {
        userAgent: '*',
        allow: [
          '/',
          '/news',
          '/news/*',
          '/services',
          '/services/*',
          '/about',
          '/contact',
        ],
        disallow: [
          '/dashboard',
          '/dashboard/*',
          '/admin',
          '/admin/*',
          '/api/auth/*',
          '/api/private/*',
          '/verify',
          '/logout',
          '/register/verify',
          '/_next/static/',
          '/.well-known/',
          '/tmp/',
          '/private/',
        ],
        crawlDelay: 1,
      },
      {
        userAgent: 'Googlebot',
        allow: [
          '/',
          '/news',
          '/news/*',
          '/services',
          '/services/*',
          '/about',
          '/contact',
          '/login',
          '/register',
        ],
        disallow: [
          '/dashboard',
          '/dashboard/*',
          '/admin',
          '/admin/*',
          '/api/auth/*',
          '/api/private/*',
        ],
      },
      {
        userAgent: 'Bingbot',
        allow: [
          '/',
          '/news',
          '/news/*',
          '/services',
          '/services/*',
          '/about',
          '/contact',
        ],
        disallow: [
          '/dashboard',
          '/dashboard/*',
          '/admin',
          '/admin/*',
          '/api/*',
        ],
      },
      // Block malicious bots
      {
        userAgent: [
          'SemrushBot',
          'AhrefsBot',
          'MJ12bot',
          'DotBot',
          'AspiegelBot',
          'SurveyBot',
          'MauiBot',
          'AlphaBot',
          'Charlie',
          'CheeseBot',
          'ChinaClaw',
          'Custo',
          'DISCo',
          'Download Demon',
          'eCatch',
          'EirGrabber',
          'EmailSiphon',
          'EmailWolf',
          'Express WebPictures',
          'ExtractorPro',
          'EyeNetIE',
          'FlashGet',
          'GetRight',
          'GetWeb!',
          'Go!Zilla',
          'Go-Ahead-Got-It',
          'GrabNet',
          'Grafula',
          'HMView',
          'Image Stripper',
          'Image Sucker',
          'Indy Library',
          'InterGET',
          'Internet Ninja',
          'JetCar',
          'JOC Web Spider',
          'larbin',
          'LeechFTP',
          'Mass Downloader',
          'MIDown tool',
          'Mister PiX',
          'Navroad',
          'NearSite',
          'NetAnts',
          'NetSpider',
          'Net Vampire',
          'NetZIP',
          'Octopus',
          'Offline Explorer',
          'Offline Navigator',
          'PageGrabber',
          'Papa Foto',
          'pavuk',
          'pcBrowser',
          'RealDownload',
          'ReGet',
          'SiteSnagger',
          'SmartDownload',
          'SuperBot',
          'SuperHTTP',
          'Surfbot',
          'tAkeOut',
          'Teleport Pro',
          'VoidEYE',
          'Web Image Collector',
          'Web Sucker',
          'WebAuto',
          'WebCopier',
          'WebFetch',
          'WebGo IS',
          'WebLeacher',
          'WebReaper',
          'WebSauger',
          'Website eXtractor',
          'Website Quester',
          'WebStripper',
          'WebWhacker',
          'WebZIP',
          'Wget',
          'Widow',
          'WWWOFFLE',
          'Xaldon WebSpider',
          'Zeus',
        ],
        disallow: '/',
      },
    ],
    sitemap: [
      `${baseUrl}/sitemap.xml`,
    ],
    host: baseUrl,
  }
} 